### ISSUE TITLE
Remove the bot from queue if it is offline for 3 or more days

### ISSUE THREAD

**Issue by Cwickks** [top-gg/issues#416]
#### Suggestion

Most of the declines is "Bot is offline". I think we should make a system(make a bot that people can invite to a server. That their bot to be approved is in. So your bot can track if a bot is offline for 3 days or more) that would remove the bots that is offline for 3 days or more in the queue because they ..

- Improve queue size and make bot approval faster
- Decrease declines with the reason of "Bot is offline"
- Make lives easier

**Comment by marcorennmaus** [comment]
Good idea but we cannot get a bot's presence unless we actually invite it
to a server due to Discord's API restrictions.

The invitation is actually where most of the time gets lost due to the
Captchas (at some point you'll get captchas for up to a minute per bot),
actually reviewing and declining a bot thats offline takes 10 seconds max

Cwickks <notifications@github.com> schrieb am Mi., 26. Aug. 2020, 07:28:

**Comment by Cwickks** [comment]
> e invitation is actually where most of the time gets lost due to the Captchas (at some point you'll get captchas for up to a minute per bot), actually reviewing and declining a bot thats offline takes 10 seconds max

What I meant is let people(people that is wanting to get their bot verified) invite a bot to their own server where the bot to be verified is in.

**Comment by Xetera** [comment]
This is a good idea but unfortunately it doesn't work with the direction were going now that we're no longer inviting bots to the server.

We will probably implement some other kind of automated measure to decrease queue size in the future but this won't be it.

**Comment by GalaxySH** [comment]
If the idea is that the bot is invited to the applicant's server, then why does the no bot policy on the DBL server matter?

And about the kicking to prevent DBL from discovering their bot is offline, just make an easy rule that removes them from the queue and nullifies their application if the DBL bot can no longer see the applicant bot.

**Comment by Xetera** [comment]
Requiring bots to be constantly seen may generate false positives that take more moderator effort to deal with. It's something to consider but it's not a solution that's as straightforward as it seems.

**Comment by GalaxySH** [comment]
While that may be true, there are possible automatic methods around that. One I can think of would be watching for the number of bots that currently have the offline timer ticking up; if the number severely spikes (indicating that it may be false and not any bot's fault) the whole thing could just be automatically reset. It would make the queue any longer than without the system.

### Alternative
Another idea would not be using a bot that DBL is charged with making and maintaining, but require bots being submitted to check in with the DBL API endpoint periodically: like once or twice a day. I think this may actually be a much better solution, you tell me.

**Comment by Xetera** [comment]
Requiring constant API interaction from developers before their bot is even approved may seem jarring and will probably be the source of a lot of confusion in the approval process. The second option is probably not viable.

Our current plan for speeding up queue times in the short term is putting together a larger team or reviewers but if we do end up needing a long term plan (since offline bots currently account for a large percentage of declines)

![Screenshot_20201016-055334.png](https://user-images.githubusercontent.com/24978328/96207489-08037780-0f74-11eb-97e1-631d34ad3a65.png)

we might end up going with a version of the first option. If we don't see a decrease in queue times —even after some changes we'll be making to our moderator team— I'll start thinking about this, thanks for your input.
