### ISSUE TITLE
Country/Main language tags

### ISSUE THREAD

**Issue by ygimenez** [top-gg/issues#460]
I think it'd be nice to have a way of searching for bots available in your native language since it'd allow even finer filtering.
This, however, would allow abuse, so I suggest to limit it to 1-3 languages at most.

**Comment by SinistreCyborg** [comment]
It would also be cool if bots can have "language tags" underneath the search tags, since many bots offer multi-language support.

**Comment by Xetera** [comment]
I'll be closing this as we have a new user-defined tags system planned for sometime next month.

**Comment by ScientiaEtVeritas** [comment]
> I'll be closing this as we have a new user-defined tags system planned for sometime next month.

The issues is closed, but in my opinion this problem is still a thing. Since one is limited to choose six tags, it's not really suitable to cover languages. Content-based tags rival language tags. When I have a bot that supports six languages, there is no space left for content-based tags. It would be nice to specify and eventually filter languages separately.
