### ISSUE TITLE
Will top.gg be making the switch to hCaptcha?

### ISSUE THREAD

**Issue by jiggey1** [top-gg/issues#599]
#### Suggestion

Alot of services have starteed to introduce hCaptcha, and since CloudFlare recently made the switch, I was wondering if top.gg was going to make the change. Of course it isnt big, however CloudFlare raises issues, like hCaptcha doesnt sell user data, etc (And i personally think it looks nicer (especially the animations 😍 )). I left the link to the article, its just a suggestion as I was wondering.

#### Applicable Links or Attachments

[Link To CloudFlare's article](https://blog.cloudflare.com/moving-from-recaptcha-to-hcaptcha/)

**Comment by Xetera** [comment]
Based on my personal experience, hCaptcha is _way_ harder on users while not being any harder for bots. The images they use are borderline undecipherable and often times I choose to leave sites that show me hcaptcha rather than struggle to solve them. It's truly awful user experience.

Captchas in general are also fairly useless at preventing automation because of captcha farms. It works very well for Cloudflare, because they're in a very unique position where their captchas are used for preventing DDoS which means it accomplishes its purpose even if bots use captcha farms to get around it which can take up to 10-12 seconds to get a response, at which point the DDoS is not as much a DDoS as it just regular traffic. That's not the case with top.gg.

Something I will be working on fairly soon is writing a good enough bot detection system that can allow us to **remove captcha**, which already doesn't do much to stop bots in the first place. If we change the captcha system at this point it'll be to remove it entirely.

I hate captchas as much as you guys do.

**Comment by Xetera** [comment]
Other captcha providers aren't really any better, like how is this a better user experience than hcaptcha lol

![image](https://user-images.githubusercontent.com/24978328/110509339-0d27b580-8113-11eb-9a28-4d40dc36b3a8.png)

I have plans for this month that don't involve captcha, if I don't see the kind of success I'm hoping with it, I'll look into different alternatives but like absolutely nobody likes captcha and you really shouldn't have to do them to vote in my opinion.

**Comment by jiggey1** [comment]
Oh ok, I really appreciate the response! I understand, and good luck with the custom bot system! Thanks -jiggey <3
