### ISSUE TITLE
New layout available

### ISSUE THREAD

**Issue by kkrypt0nn** [top-gg/issues#641]
#### Expected Behavior

I expected to see the layout of the, current, released home page.

#### Observed Behavior

I see the layout of the future (beta) home page.

#### Applicable Links or Attachments

![image](https://user-images.githubusercontent.com/43011723/116360307-11617c80-a800-11eb-9a4a-d1fbf3fdfffe.png)

#### Steps to Reproduce

1. Open top.gg
2. Go to a page that will give you an error, example: top.gg/this-page-does-not-exist
3. Click on "Go Home"
4. You know see the future layout of top.gg

#### Web Browser and Version

Microsoft Edge - Version 90.0.818.49 (Official build) (64-bit)

#### Operating System and Version

Windows 10

#### Screen Resolution

3440x1440

**Comment by goverfl0w** [comment]
poggers

**Comment by Xetera** [comment]
This is just a visual bug, not a big priority atm since the new design isn't a secret. Just reload the page

**Comment by jpbberry** [comment]
I think this issue should stay open and the "functionality" reversed. This seems like more of a bug rather than a feature.
When hitting the Go Home button it actively hinders the page as well, making the user forcefully scroll down a bit, in the past it even disabled their ability to scroll. It's also just a weird random transition rather than some Easter egg. Considering the Go Home button is something a legitimate user would use it shouldn't act so sporadically.

**Comment by velddev** [comment]
It's a wontfix
