### ISSUE TITLE
A system to highlight small bots

### ISSUE THREAD

**Issue by lumap** [top-gg/issues#726]
### Suggestion

I suggest adding a system to highlight some random small bots on the website. 

The current auction system rewards big bots more than anything else, and small bots are not advantaged in any way as they can struggle getting 100 votes and/or winning an auction since most of the bots that do auctions spend actual money on auctions.

I think that a system where once per day 1 or 2 random bots with less than 1k servers gets a "highlighted" spot on the main page would be a good way for small bots to get a chance to grow. It's probably not the best example, but that's the best one I can think of.

**Comment by jpbberry** [comment]
Frankly I just don’t think this is a good idea. At least the way you propose it being implemented. Front page is something that is made for the common user to find bots that have gained those spots. This is just how life is. You would never see another featurer like google do something like this. If you want your service to do well, you either have to pay or make it good enough to garner the users. However this did spark an idea, I was thinking of a “hot” or “trending” page. That would look for over average growth from bots via clicks (because api posted things can’t really be trusted). If a bot has a high**er** amount of unique traffic, or high**er** vote income, they could be put onto that hot page, and that would actually attract users into looking into those bots. Food for though.

**Comment by marcorennmaus** [comment]
Stable already had a similar section to this (Trending New, although that one also had its issues), It seems to be missing from the Beta page though and I'm not sure if something similar is still planned to be added later on or not.

**Comment by TAG-Epic** [comment]
@jpbberry what would stop someone from spam clicking on their own bot/server, although I really like the idea. Maybe a max time you can be on there for aswell so one bot doesn't sit there forever?

**Comment by jpbberry** [comment]
@TAG-Epic 
> trusted). If a bot has a higher amount of **unique** traffic,
