### ISSUE TITLE
401 Error for token event tho it is valid

### ISSUE THREAD

**Issue by alputv** [top-gg/issues#735]
#### Expected Behavior
Endpoint working just fine (and not returning errors)

#### Observed Behavior
Returning 401 error

#### Applicable Links or Attachments
![image](https://user-images.githubusercontent.com/77716705/122670486-09540680-d1cb-11eb-80c9-6baee695e6bd.png)

**Comment by Xignotic84** [comment]
This seems to be an issue with either not providing any token at all or the token you've provided is invalid, this also could be an issue with the library you are using. Because of this I recommend seeking assistance in our topgg-api channel to see if you can identify the potential cause and if it is indeed an issue with the library, you can create a GitHub issue for it [here](https://github.com/top-gg/node-sdk/issues)
