### ISSUE TITLE
Suggestions for the oauth login link

### ISSUE THREAD

**Issue by TheLimifiedLime** [top-gg/issues#744]
#### Suggestions

Suggestion #1:
Update the oauth login link to the **discord.com** domain instead of the old **discordapp.com** domain

- Since Discord will redirect you anyways I think you might as well skip that part. I also don't think it would take too much effort.

Suggestion #2:
Add `prompt=none` as a oauth login link parameter

- Would make the login process much faster after you authorize once in my opinion. I also doubt it would be much effort to do either.

#### Applicable Links or Attachments

None

**Comment by Luke-6723** [comment]
Suggestion 1: 
This is probably planned / will likely get fixed in beta.

Suggestion 2:
Whilst I agree it would be nice. Having it there by default could cause issues and the amount of users in support who complain about things such as not being able to see their bot are sometimes logged into the wrong account. This would cause more issues as people wouldn't see the account they are logged into before it even logs them in

I would probably suggest adding a toggle for users to enable this and then set a cookie for users who want a quicker login to have this functionality. Otherwise it's not really pheasable without causing more issues in support

**Comment by TheLimifiedLime** [comment]
Yeah a toggle for it would be good idea

**Comment by Xetera** [comment]
We implemented `prompt=none` before and it didn't work well by itself. We're probably going to add it back later and make it so logging out manually removes `prompt=none` from the login url the next time you want to login so you can log back in faster if your session expires.
