### ISSUE TITLE
User ID URLs working with invalid ID's

### ISSUE THREAD

**Issue by bchurton** [top-gg/issues#836]
Hey!

Found an issue regarding URLs (https://top.gg/user/USERID) where some Users have duplicate pages. 

For example, tj (userid 749936830098571335)'s user page can be access from both https://top.gg/user/749936830098571335 (real id) and https://top.gg/user/7772600571914813440 (shouldn't be possible, id doesn't exist).

Another example is Family Friendly (userid 286224826170081290) can be found at both https://top.gg/user/286224826170081290 (real id) and https://top.gg/user/3507461555350077440 (shouldn't be possible, id doesn't exist)

**Comment by Xignotic84** [comment]
This is because the second ID is their Top.gg ID, this is unique to the user and generated by us and not by Discord. We currently support both Discord ID's and Top.gg ID's for the URL's.

**Comment by Hopefuls** [comment]
Not a bug, but actually intentional, lemme explain:

Every user on top.gg gets assigned a so called "Top.gg user id" upon first logging into top.gg. That id is the main id used for top.gg site stuff. But you would also have a discord based id, which is also linked to your top.gg account. The decision was made to also allow viewing your profile using your discord id.

You could also try that yourself: 
- go to your profile (https://top.gg/user/discordid)
- open any of your bots
- click yourself on the creators

You should now be on your top.gg based id.
